# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'CustomAudioExp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CustomAudioExp

  pod 'FirebaseUI'
  pod 'SDWebImageSwiftUI'
  pod 'Alamofire', '~> 5.4'

  target 'CustomAudioExpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CustomAudioExpUITests' do
    # Pods for testing
  end

end
